### ISSUE TITLE
500 error when owners/new

### ISSUE THREAD

**Issue by JasonMrX** [glts/safer-spring-petclinic#1]
Hi there,

I am using this tutorial to learn checker but I am new to Java, Spring, maven..basically everything. So my issue might sound silly, but please help.

I was at the very beginning of the tutorial and was playing around with the deployed app on my browser, but when I tried to add new owner by clicking on the "new owner" hyperlink, I got a 500. Here is the stack trace I had:

org.apache.jasper.JasperException: /WEB-INF/jsp/owners/createOrUpdateOwnerForm.jsp (line: 24, column: 8) No tag "inputField" defined in tag library imported with prefix "petclinic"
    org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
    org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:443)
    org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:199)
    org.apache.jasper.compiler.Parser.parseCustomTag(Parser.java:1215)
    org.apache.jasper.compiler.Parser.parseElements(Parser.java:1452)
    org.apache.jasper.compiler.Parser.parseBody(Parser.java:1664)
    org.apache.jasper.compiler.Parser.parseOptionalBody(Parser.java:1002)
    org.apache.jasper.compiler.Parser.parseCustomTag(Parser.java:1274)
    org.apache.jasper.compiler.Parser.parseElements(Parser.java:1452)
    org.apache.jasper.compiler.Parser.parse(Parser.java:138)
    org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
    org.apache.jasper.compiler.ParserController.parse(ParserController.java:102)
    org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:198)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:373)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:353)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:340)
    org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:646)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
    org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
    org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
    org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1244)
    org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
    com.github.dandelion.datatables.core.web.filter.DatatablesFilter.doFilter(DatatablesFilter.java:74)
    com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:128)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

Much appreciated!

Jason

**Comment by glts** [comment]
Jason,
can you add some info about your setup? Operating system, Java version (`java -version`), Maven version (`mvn --version`), and what command you used to build the project and start the web server?

**Comment by JasonMrX** [comment]
Here is my Java version

```
jiasen@Jiasen-PC:~/Desktop/checker-framework/safer-spring-petclinic$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

And my maven version. I just installed the maven 3.

```
jiasen@Jiasen-PC:~/Desktop/checker-framework/safer-spring-petclinic$ mvn --version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T12:37:52-05:00)
Maven home: /usr/share/maven3
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-85-generic", arch: "amd64", family: "unix"
```

Build the project

```
mvn install
```

Deploy on server

```
mvn tomcat7:run
```

I think they are exactly the same as your tutorial in wiki

**Comment by glts** [comment]
Ah yeah that’s too bad, I can reproduce this on Ubuntu 14.04. Looks like the Pet Clinic snapshot I based this tutorial on has a broken JSP compilation in some situations.

That’s really unfortunate. I can’t do anything about that now, but what I can say is that browsing around the app in the browser isn’t actually necessary for this tutorial as it’s about the quality of the code itself. You can skip the `mvn tomcat7:run` step without missing anything. cheers.

**Comment by JasonMrX** [comment]
Great. Thanks for the advice.
